### ISSUE TITLE
Add provider: itch.io

### ISSUE THREAD

**Issue by chandler05** [Raicuparta/rai-pal#56]

**Comment by Raicuparta** [comment]
Good point, although I feel like the majority of people don't use the itch.io app, they just download games manually. In that case, the only option would be to add that game manually (#51). So this one will probably be quite low priority.

**Comment by Raicuparta** [comment]
some information I gathered, for future reference:
- owned games can be retrieved by reading the sqlite database in `AppData\Roaming\itch\db\butler.db`. Make sure it includes the data in `butler.db-wal` too.
- installed game data can be retrieved by parsing all files in `AppData\Roaming\itch\apps\*\.itch\receipt.json.gz` (need to decompress first).
- games from large bundles aren't automatically included as owned. There are scripts to do this, but they are pretty slow, and not recommended by the itch team, since it fills your library with trash. Example: https://gist.github.com/lats/c920866caf9c0cb04e82abba411e1bb9

**Comment by Karf** [comment]
+1 for this. I'm one of the fools who has filled his library with trash, as is _my god given right to be stupid_. Obviously this is a very low prio feature, but it would be nice for people who have a large amount of stuff on itch - being able to sort by the options Rai Pal provides would be nice (let's be real, mainly trying to sort by Engine versions)

**Comment by Raicuparta** [comment]
I actually have this working already, just haven't included it in an update because it's pretty slow to check for engines of all the trash I have on itch. So I'm working on making it a bit faster first, and making it so you don't have to wait for every provider to finish.
